### PR TITLE
Do not detect syntax by extension

### PR DESCRIPTION
**Pull request by faergeek**
Change the way syntax is detected.
Now it will work for buffers which not saved to file yet.

### CODE REVIEW

**Comment by lnikell** [comment]
sublime 3

**Comment by faergeek** [comment]
Is there anything in console may be?

**Comment by lnikell** [comment]
when i print(self.view.match_selector(0, 'source.sass'))
it return False

OS: Windows 10

**Comment by faergeek** [comment]
What do you use for sass syntax highlighting?

**Comment by lnikell** [comment]
Oh, yes. I did not install sass package on this pc.

**Pull request merged**
